### ISSUE TITLE
App not compiling with the latest CaptureSDK

### ISSUE THREAD

**Issue by kevinbruneau** [SocketMobile/capturesingleentryswift-ios#1]
Steps to reproduce:
1 - Perform a fresh clone of the repo.
2 - Run pod install in the project folder
3 - Try to compile the app
- > Error in MasterViewController line 98 : SKTAppInfo has no member appId.

The app use the version 1.0.X in the cocoaPods. Is it possible that there is a newer version of the SDK but it was not made available on cocoaPods?

**Comment by EricGlaenzer** [comment]
Hi kevinbruneau,
Thank you for pointing this out. The Podfile.lock was not committed with the latest update to use the new Capture cocoapods. Please try again with this new version.
