### ISSUE TITLE
Ionic

### ISSUE THREAD

**Issue by davidseek** [SocketMobile/capturesingleentryswift-ios#4]
I'm thinking about reworking our native iOS App with Ionic.
Is there a way to capture from the SocketMobile scanners with Ionic?
My research so far did not return anything.

Help is appreciated.

**Comment by socketPM** [comment]
Not yet. We are working on a Javascript based solution. But it will take sometime to push out. Any requests or suggestions?

Thanks

**Comment by davidseek** [comment]
Well. For me it falls or stand on that right now. I have an App in production for inspections and your API is provided for our Users who want to use the scanners to scan barcodes. 

Do you think the kit will be out in the next 1-2 months? Otherwise open sourcing so one can help to get it done faster would be good. 

All I need is connecting to scanner and get the scanned codes.

**Comment by EricGlaenzer** [comment]
Hi David,
I am assuming your primary target device is iOS? Also do you plan to use Capacitor or Cordova? I will get back to you end of this week about the estimate.
Thanks.

**Comment by davidseek** [comment]
Right now we only do iOS. 
With Ionic it’s the idea then to support both. 
And through Ionic it’s Cordova. 

I thank you for taking the time. 
David

**Comment by davidseek** [comment]
Any updates on this?

**Comment by EricGlaenzer** [comment]
Hi David,
Sorry for not replying sooner. We should have something to play with around 5/14. It will have only the basic decoded data, device arrival, device removal events.

**Comment by davidseek** [comment]
That's perfect. 
Time wise it's perfect and also the events are absolutely sufficient for my needs.
Appreciate it.

**Comment by EricGlaenzer** [comment]
We have released a basic version of Capture for Ionic/Cordova app. See https://github.com/SocketMobile/capturebasic-cordova-ios

**Comment by davidseek** [comment]
Hey @EricGlaenzer 

Do you have anything on the roadmap for Capacitor?

**Comment by sokulski** [comment]
Hey @EricGlaenzer.

Are you still involved with Socket Mobile?

Can you speak to any plans for a Capacitor plugin to support the newer versions of Ionic?

**Comment by socketPM** [comment]
@sokulski Yes, @EricGlaenzer is still involved with Socket Mobile :). Re your question, our current plan is to get the Capacitor plugin some time around July. Thanks.

**Comment by sokulski** [comment]
Wonderful @socketPM. Looking forward to it!
